/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of LMDB.xs. Do not edit this file, edit LMDB.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "LMDB.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#ifdef	SV_UNDEF_RETURNS_NULL
#define MySvPV(sv, len)	    SvPV_flags(sv, len, SV_GMAGIC|SV_UNDEF_RETURNS_NULL)
#else
#define	MySvPV(sv, len)	    SvOK(sv)?SvPV_flags(sv, len, SV_GMAGIC):((len=0), NULL)
#endif

#ifndef cxinc
#define cxinc()	Perl_cxinc(aTHX)
#endif

#include <lmdb.h>
#include "const-c.inc"

#define	F_ISSET(w, f)	(((w) & (f)) == (f))

typedef IV MyInt;

#define StoreUV(k, v)	hv_store(RETVAL, (k), strlen(k), newSVuv(v), 0)

static void
populateStat(pTHX_ HV** hashptr, int res, MDB_stat *stat)
{
    HV* RETVAL;
    if(res) 
	croak(mdb_strerror(res), NULL);
    RETVAL = newHV();
    StoreUV("psize", stat->ms_psize);
    StoreUV("depth", stat->ms_depth);
    StoreUV("branch_pages", stat->ms_branch_pages);
    StoreUV("leaf_pages", stat->ms_leaf_pages);
    StoreUV("overflow_pages", stat->ms_overflow_pages);
    StoreUV("entries", stat->ms_entries);
    *hashptr = RETVAL;
}

typedef	MDB_env*    LMDB__Env;
typedef	MDB_txn*    LMDB__Txn;
typedef	MDB_txn*    TxnOrNull;
typedef	MDB_dbi	    LMDB;
typedef	MDB_val	    DBD;
typedef	MDB_val	    DBK;
typedef	MDB_val	    DBKC;
typedef	MDB_cursor* LMDB__Cursor;
typedef	unsigned int flags_t;

static GV *my_lasterr;
static GV *my_errgv;
#define DieOnErr    SvTRUE(GvSV(my_errgv))

#define MY_CXT_KEY  "LMDB_File::_guts" XS_VERSION
typedef struct {
    AV *currdb;
    unsigned int cflags;
    SV *my_asv;
    SV *my_bsv;
    OP *lmdb_dcmp_cop;
} my_cxt_t;

START_MY_CXT

#define MY_CMP	    *av_fetch(MY_CXT.currdb, 2, 1)
#define MY_DCMP	    *av_fetch(MY_CXT.currdb, 3, 1)
#define FAST_MODE   SvTRUE(*av_fetch(MY_CXT.currdb, 5, 1))
#define PRED_FLGS   mdb_dbi_flags(txn, dbi, &MY_CXT.cflags)
#define dCURSOR	    MDB_txn* txn; MDB_dbi dbi
#define PREC_FLGS(c) txn = mdb_cursor_txn(c); dbi = mdb_cursor_dbi(c); PRED_FLGS
#define ISDBKINT    F_ISSET(MY_CXT.cflags, MDB_INTEGERKEY)
#define ISDBDINT    F_ISSET(MY_CXT.cflags, MDB_DUPSORT|MDB_INTEGERDUP)

static void
sv_setstatic(pTHX_ SV *const sv, MDB_val *data)
{
    dMY_CXT;
    if(ISDBDINT)
	    sv_setiv_mg(sv, *(MyInt *)data->mv_data);
    else {
	if(FAST_MODE) {
	    SV_CHECK_THINKFIRST_COW_DROP(sv);
	    SvUPGRADE(sv, SVt_PV);
	    if (SvPVX_const(sv))
		SvPV_free(sv);

	    SvCUR_set(sv, data->mv_size);
	    SvPV_set(sv, data->mv_data);
	    SvLEN_set(sv, 0); /* Tell Perl not to free memory */
	    SvPOK_only(sv);
	    SvREADONLY_on(sv);
	} else {
	    sv_setpvn_mg(sv, data->mv_data, data->mv_size);
	    SvUTF8_off(sv);
	}
    }
}

/* Callback handling */

static int
LMDB_cmp(const MDB_val *a, const MDB_val *b) {
    dTHX;
    dMY_CXT;
    dSP;
    int ret;
    ENTER; SAVETMPS;
    PUSHMARK(SP);
    sv_setpvn_mg(MY_CXT.my_asv, a->mv_data, a->mv_size);
    sv_setpvn_mg(MY_CXT.my_bsv, b->mv_data, b->mv_size);
    call_sv(SvRV(MY_CMP), G_SCALAR|G_NOARGS);
    SPAGAIN;
    ret = POPi;
    PUTBACK;
    FREETMPS; LEAVE;
    return ret;
}

#define dMCOMMON        \
    dMY_CXT;	         \
    int needsave = 0;	  \
    SV *my_cmpsv = MY_CMP; \
    SV *my_dcmpsv = MY_DCMP

#define MY_PUSH_COMMON \
    if(SvROK(my_cmpsv) && SvTYPE(SvRV(my_cmpsv)) == SVt_PVCV) {	    \
	mdb_set_compare(txn, dbi, LMDB_cmp);			    \
	needsave++;						    \
    }								    \
    if(needsave) {						    \
	SAVESPTR(MY_CXT.my_asv);				    \
	SAVESPTR(MY_CXT.my_bsv);				    \
    }

#ifdef dMULTICALL
/* If this perl has MULTICALL support, use it for the DATA comparer */
static int
LMDB_dcmp(const MDB_val *a, const MDB_val *b) {
    dTHX;
    dMY_CXT;
    sv_setpvn_mg(MY_CXT.my_asv, a->mv_data, a->mv_size);
    sv_setpvn_mg(MY_CXT.my_bsv, b->mv_data, b->mv_size);
    PL_op = MY_CXT.lmdb_dcmp_cop;
    CALLRUNOPS(aTHX);
    return SvIV(*PL_stack_sp);
}

#define dMY_MULTICALL \
    dMCOMMON;          \
    dMULTICALL;         \
    I32 gimme = G_SCALAR

#define MY_PUSH_MULTICALL \
    multicall_cv = NULL;   \
    if(SvROK(my_dcmpsv) && SvTYPE(SvRV(my_dcmpsv)) == SVt_PVCV) {   \
	PUSH_MULTICALL((CV *)SvRV(my_dcmpsv));			    \
	MY_CXT.lmdb_dcmp_cop = multicall_cop;			    \
	mdb_set_dupsort(txn, dbi, LMDB_dcmp);			    \
	needsave++;						    \
    }								    \
    MY_PUSH_COMMON

#define MY_POP_MULTICALL    \
    if(multicall_cv) {            \
	POP_MULTICALL; newsp = newsp;  \
    }

#else /* NO MULTICALL support, use a slow path */

static int
LMDB_dcmp(const MDB_val *a, const MDB_val *b) {
    dTHX;
    dMY_CXT;
    dSP;
    int ret;
    ENTER; SAVETMPS;
    PUSHMARK(SP);
    sv_setpvn_mg(MY_CXT.my_asv, a->mv_data, a->mv_size);
    sv_setpvn_mg(MY_CXT.my_bsv, b->mv_data, b->mv_size);
    call_sv(SvRV(MY_DCMP), G_SCALAR|G_NOARGS);
    SPAGAIN;
    ret = POPi;
    PUTBACK;
    FREETMPS; LEAVE;
    return ret;
}

#define dMY_MULTICALL  dMCOMMON

#define MY_PUSH_MULTICALL \
    if(SvROK(my_dcmpsv) && SvTYPE(SvRV(my_dcmpsv)) == SVt_PVCV) {   \
	mdb_set_dupsort(tx, dbi, LMDB_dcmp);			    \
	needsave++;						    \
    }								    \
    MY_PUSH_COMMON

#define MY_POP_MULTICALL

#endif	/* dMULTICALL */

#define ProcError(res)   \
    if(res) {					\
	sv_setiv(GvSV(my_lasterr), res);	\
	SV *sv = newSVpv(mdb_strerror(res),0);	\
	SvSetSV(ERRSV, sv);			\
	if(DieOnErr) croak(NULL);		\
	XSRETURN_IV(res);			\
    }

#line 223 "LMDB.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 365 "LMDB.c"

XS_EUPXS(XS_LMDB__Env_create); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_create)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "env");
    {
	LMDB__Env	env;
	int	RETVAL;
	dXSTARG;

	RETVAL = mdb_env_create(&env);
#line 219 "LMDB.xs"
	ProcError(RETVAL);
#line 381 "LMDB.c"
	sv_setref_pv(ST(0), "LMDB::Env", (void*)env);
	SvSETMAGIC(ST(0));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_open); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_open)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "env, path, flags, mode");
    {
	LMDB__Env	env;
	const char *	path = (const char *)SvPV_nolen(ST(1))
;
	flags_t	flags =	SvOK(ST(2)) ? (flags_t)SvUV(ST(2)) : 0
;
	int	mode = (int)SvIV(ST(3))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::open",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_open(env, path, flags, mode);
#line 230 "LMDB.xs"
	ProcError(RETVAL);
#line 420 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_copy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_copy)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, path");
    {
	LMDB__Env	env;
	const char *	path = (const char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::copy",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_copy(env, path);
#line 237 "LMDB.xs"
	ProcError(RETVAL);
#line 453 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_copyfd); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_copyfd)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, fd");
    {
	LMDB__Env	env;
	mdb_filehandle_t	fd = PerlIO_fileno(IoOFP(sv_2io(ST(1))))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::copyfd",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_copyfd(env, fd);
#line 244 "LMDB.xs"
	ProcError(RETVAL);
#line 486 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_stat); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_stat)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "env");
    {
	LMDB__Env	env;
#line 250 "LMDB.xs"
	MDB_stat stat;
#line 503 "LMDB.c"
	HV *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::stat",
			"env", "LMDB::Env")
;
#line 252 "LMDB.xs"
	populateStat(aTHX_ &RETVAL, mdb_env_stat(env, &stat), &stat);
#line 517 "LMDB.c"
        ST(0) = newRV_noinc((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_info); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_info)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "env");
    {
	LMDB__Env	env;
#line 260 "LMDB.xs"
	MDB_envinfo stat;
	int res;
#line 536 "LMDB.c"
	HV *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::info",
			"env", "LMDB::Env")
;
#line 263 "LMDB.xs"
	res = mdb_env_info(env, &stat);
	ProcError(res);
	RETVAL = newHV();
	StoreUV("mapaddr", (uintptr_t)stat.me_mapaddr);
	StoreUV("mapsize", stat.me_mapsize);
	StoreUV("last_pgno", stat.me_last_pgno);
	StoreUV("last_txnid", stat.me_last_txnid);
	StoreUV("maxreaders", stat.me_maxreaders);
	StoreUV("numreaders", stat.me_numreaders);
#line 558 "LMDB.c"
        ST(0) = newRV_noinc((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_sync); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_sync)
{
    dVAR; dXSARGS;
    if (items < 1 || items > 2)
       croak_xs_usage(cv,  "env, force=0");
    {
	LMDB__Env	env;
	int	force;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::sync",
			"env", "LMDB::Env")
;

	if (items < 2)
	    force = 0;
	else {
	    force = (int)SvIV(ST(1))
;
	}

	RETVAL = mdb_env_sync(env, force);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_close); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_close)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "env");
    {
	LMDB__Env	env;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::close",
			"env", "LMDB::Env")
;

	mdb_env_close(env);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_LMDB__Env_set_flags); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_set_flags)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "env, flags, onoff");
    {
	LMDB__Env	env;
	unsigned int	flags = (unsigned int)SvUV(ST(1))
;
	int	onoff = (int)SvIV(ST(2))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::set_flags",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_set_flags(env, flags, onoff);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_get_flags); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_get_flags)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, flags");
    {
	LMDB__Env	env;
	unsigned int	flags;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::get_flags",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_get_flags(env, &flags);
	sv_setuv(ST(1), (UV)flags);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_get_path); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_get_path)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, path");
    {
	LMDB__Env	env;
	const char *	path;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::get_path",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_get_path(env, &path);
	sv_setpv((SV*)ST(1), path);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_set_mapsize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_set_mapsize)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, size");
    {
	LMDB__Env	env;
	size_t	size = (size_t)SvUV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::set_mapsize",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_set_mapsize(env, size);
#line 309 "LMDB.xs"
	ProcError(RETVAL);
#line 747 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_set_maxreaders); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_set_maxreaders)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, readers");
    {
	LMDB__Env	env;
	unsigned int	readers = (unsigned int)SvUV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::set_maxreaders",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_set_maxreaders(env, readers);
#line 316 "LMDB.xs"
	ProcError(RETVAL);
#line 780 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_get_maxreaders); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_get_maxreaders)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, readers");
    {
	LMDB__Env	env;
	unsigned int	readers;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::get_maxreaders",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_get_maxreaders(env, &readers);
	sv_setuv(ST(1), (UV)readers);
	SvSETMAGIC(ST(1));
#line 325 "LMDB.xs"
	ProcError(RETVAL);
#line 814 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_set_maxdbs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_set_maxdbs)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, dbs");
    {
	LMDB__Env	env;
	int	dbs = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::set_maxdbs",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_set_maxdbs(env, dbs);
#line 332 "LMDB.xs"
	ProcError(RETVAL);
#line 847 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_get_maxkeysize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_get_maxkeysize)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "env");
    {
	LMDB__Env	env;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::get_maxkeysize",
			"env", "LMDB::Env")
;

	RETVAL = mdb_env_get_maxkeysize(env);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Env_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Env_id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "env");
    {
	LMDB__Env	env;
	UV	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Env::id",
			"env", "LMDB::Env")
;
#line 342 "LMDB.xs"
	RETVAL = (UV)env;
#line 904 "LMDB.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Txn__begin); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Txn__begin)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "env, parent, flags, txn");
    {
	LMDB__Env	env;
	TxnOrNull	parent;
	flags_t	flags =	SvOK(ST(2)) ? (flags_t)SvUV(ST(2)) : 0
;
	LMDB__Txn	txn;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Txn::_begin",
			"env", "LMDB::Env")
;

        if(!SvTRUE(ST(1))) {
            parent = (TxnOrNull) NULL;
        } else if (SvROK(ST(1)) && sv_derived_from(ST(1), "LMDB::Txn")) {
            IV tmp = SvIV((SV*)SvRV(ST(1)));
            parent = INT2PTR(TxnOrNull,tmp);
        }
        else
            Perl_croak(aTHX_ "%s: %s is not of type %s",
                        "LMDB::Txn::_begin",
                        "parent", "LMDB::Txn")
;

	RETVAL = mdb_txn_begin(env, parent, flags, &txn);
#line 355 "LMDB.xs"
	ProcError(RETVAL);
#line 951 "LMDB.c"
	sv_setref_pv(ST(3), "LMDB::Txn", (void*)txn);
	SvSETMAGIC(ST(3));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Txn__env); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Txn__env)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "txn");
    {
	LMDB__Txn	txn;
	UV	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Txn::_env",
			"txn", "LMDB::Txn")
;
#line 363 "LMDB.xs"
	RETVAL= (UV)mdb_txn_env(txn);
#line 982 "LMDB.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Txn__commit); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Txn__commit)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "txn");
    {
	LMDB__Txn	txn;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Txn::_commit",
			"txn", "LMDB::Txn")
;

	RETVAL = mdb_txn_commit(txn);
#line 371 "LMDB.xs"
	ProcError(RETVAL);
#line 1013 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Txn__abort); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Txn__abort)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "txn");
    {
	LMDB__Txn	txn;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Txn::_abort",
			"txn", "LMDB::Txn")
;

	mdb_txn_abort(txn);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_LMDB__Txn__reset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Txn__reset)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "txn");
    {
	LMDB__Txn	txn;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Txn::_reset",
			"txn", "LMDB::Txn")
;

	mdb_txn_reset(txn);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_LMDB__Txn__renew); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Txn__renew)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "txn");
    {
	LMDB__Txn	txn;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Txn::_renew",
			"txn", "LMDB::Txn")
;

	RETVAL = mdb_txn_renew(txn);
#line 385 "LMDB.xs"
	ProcError(RETVAL);
#line 1094 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Txn__id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Txn__id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "txn");
    {
	LMDB__Txn	txn;
	UV	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Txn::_id",
			"txn", "LMDB::Txn")
;
#line 391 "LMDB.xs"
	RETVAL = (UV)txn;
#line 1123 "LMDB.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor_open); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor_open)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "txn, dbi, cursor");
    {
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	LMDB__Cursor	cursor;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::open",
			"txn", "LMDB::Txn")
;

	RETVAL = mdb_cursor_open(txn, dbi, &cursor);
	sv_setref_pv(ST(2), "LMDB::Cursor", (void*)cursor);
	SvSETMAGIC(ST(2));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor_close); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor_close)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cursor");
    {
	LMDB__Cursor	cursor;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::close",
			"cursor", "LMDB::Cursor")
;

	mdb_cursor_close(cursor);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_LMDB__Cursor_count); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor_count)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cursor, count");
    {
	LMDB__Cursor	cursor;
	UV	count;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::count",
			"cursor", "LMDB::Cursor")
;

	RETVAL = mdb_cursor_count(cursor, &count);
	sv_setuv(ST(1), (UV)count);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor_dbi); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor_dbi)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cursor");
    {
	LMDB__Cursor	cursor;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::dbi",
			"cursor", "LMDB::Cursor")
;

	RETVAL = mdb_cursor_dbi(cursor);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor_del); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor_del)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cursor, flags");
    {
	LMDB__Cursor	cursor;
	flags_t	flags =	SvOK(ST(1)) ? (flags_t)SvUV(ST(1)) : 0
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::del",
			"cursor", "LMDB::Cursor")
;

	RETVAL = mdb_cursor_del(cursor, flags);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor_renew); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor_renew)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "txn, cursor");
    {
	LMDB__Txn	txn;
	LMDB__Cursor	cursor;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::renew",
			"txn", "LMDB::Txn")
;

	if (SvROK(ST(1)) && sv_derived_from(ST(1), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::renew",
			"cursor", "LMDB::Cursor")
;

	RETVAL = mdb_cursor_renew(txn, cursor);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor_txn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor_txn)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cursor");
    {
	LMDB__Cursor	cursor;
	UV	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::txn",
			"cursor", "LMDB::Cursor")
;
#line 434 "LMDB.xs"
	RETVAL = (UV)mdb_cursor_txn(cursor);
#line 1338 "LMDB.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor__get); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor__get)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "cursor, key, data, op");
    {
#line 443 "LMDB.xs"
	dMY_MULTICALL;
	dCURSOR;
#line 1355 "LMDB.c"
	LMDB__Cursor	cursor;
	DBKC	key;
	DBD	data;
	MDB_cursor_op	op = (MDB_cursor_op)SvIV(ST(3))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::_get",
			"cursor", "LMDB::Cursor")
;

	 PREC_FLGS(cursor);

	if (ISDBKINT) {
	    if(SvOK(ST(1))) {
		SvIV_please(ST(1));
		key.mv_data = &(((XPVIV*)SvANY(ST(1)))->xiv_iv);
	    } else key.mv_data = (MyInt *)"\0\0\0\0\0\0\0\0";
	    key.mv_size = sizeof(MyInt);
	}
	else if(SvOK(ST(1))) key.mv_data = SvPV(ST(1), key.mv_size)
;

	if (ISDBDINT) {
	    SvIV_please(ST(2));
	    data.mv_data = &(((XPVIV*)SvANY(ST(2)))->xiv_iv);
	    data.mv_size = sizeof(MyInt);
	}
	else data.mv_data = MySvPV(ST(2), data.mv_size)
;
#line 451 "LMDB.xs"
	MY_PUSH_MULTICALL;
#line 1395 "LMDB.c"

	RETVAL = mdb_cursor_get(cursor, &key, &data, op);
#line 453 "LMDB.xs"
	MY_POP_MULTICALL;
	ProcError(RETVAL);
#line 1401 "LMDB.c"
	if(op != MDB_SET) {
	    if(ISDBKINT) {
		sv_setiv_mg(ST(1), *(MyInt *)key.mv_data);
	    } else {
		sv_setpvn_mg(ST(1), key.mv_data, key.mv_size);
		SvUTF8_off(ST(1));
	    }
	}
	SvSETMAGIC(ST(1));
	sv_setstatic(aTHX_ ST(2), &data);
	SvSETMAGIC(ST(2));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB__Cursor__put); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB__Cursor__put)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "cursor, key, data, flags");
    {
#line 462 "LMDB.xs"
	dMY_MULTICALL;
	dCURSOR;
#line 1429 "LMDB.c"
	LMDB__Cursor	cursor;
	DBKC	key;
	DBD	data;
	flags_t	flags =	SvOK(ST(3)) ? (flags_t)SvUV(ST(3)) : 0
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Cursor")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    cursor = INT2PTR(LMDB__Cursor,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB::Cursor::_put",
			"cursor", "LMDB::Cursor")
;

	 PREC_FLGS(cursor);

	if (ISDBKINT) {
	    if(SvOK(ST(1))) {
		SvIV_please(ST(1));
		key.mv_data = &(((XPVIV*)SvANY(ST(1)))->xiv_iv);
	    } else key.mv_data = (MyInt *)"\0\0\0\0\0\0\0\0";
	    key.mv_size = sizeof(MyInt);
	}
	else if(SvOK(ST(1))) key.mv_data = SvPV(ST(1), key.mv_size)
;

	if (ISDBDINT) {
	    SvIV_please(ST(2));
	    data.mv_data = &(((XPVIV*)SvANY(ST(2)))->xiv_iv);
	    data.mv_size = sizeof(MyInt);
	}
	else data.mv_data = MySvPV(ST(2), data.mv_size)
;
#line 470 "LMDB.xs"
	MY_PUSH_MULTICALL;
#line 1469 "LMDB.c"

	RETVAL = mdb_cursor_put(cursor, &key, &data, flags);
#line 472 "LMDB.xs"
	MY_POP_MULTICALL;
	ProcError(RETVAL);
#line 1475 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

/* INCLUDE:  Including 'const-xs.inc' from 'LMDB.xs' */


XS_EUPXS(XS_LMDB_File_constant); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File_constant)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	const char	*pv;
#line 1508 "LMDB.c"
	SV *	sv = ST(0)
;
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv, &pv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid LMDB_File macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined LMDB_File macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break;
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing LMDB_File macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 1585 "LMDB.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'LMDB.xs' from 'const-xs.inc' */

#ifdef __GNUC__
#pragma GCC diagnostic warning "-Wmaybe-uninitialized"
#endif

XS_EUPXS(XS_LMDB_File__setcurrent); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__setcurrent)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "currdb");
    {
	AV*	currdb;
#line 491 "LMDB.xs"
	dMY_CXT;
#line 1608 "LMDB.c"

	STMT_START {
		SV* const xsub_tmp_sv = ST(0);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    currdb = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak(aTHX_ "%s: %s is not an ARRAY reference",
				"LMDB_File::_setcurrent",
				"currdb");
		}
	} STMT_END
;
#line 493 "LMDB.xs"
	MY_CXT.currdb = currdb;
#line 1625 "LMDB.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_LMDB_File__dbi_open); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__dbi_open)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "txn, name, flags, dbi");
    {
	LMDB__Txn	txn;
	const char *	name = SvOK(ST(1)) ? (const char *)SvPV_nolen(ST(1)) : NULL;
	flags_t	flags =	SvOK(ST(2)) ? (flags_t)SvUV(ST(2)) : 0
;
	LMDB	dbi;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_dbi_open",
			"txn", "LMDB::Txn")
;

	RETVAL = mdb_dbi_open(txn, name, flags, &dbi);
#line 502 "LMDB.xs"
	ProcError(RETVAL);
#line 1659 "LMDB.c"
	sv_setpvn(ST(3), (char *)&dbi, sizeof(dbi));
	SvSETMAGIC(ST(3));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__stat); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__stat)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "txn, dbi");
    {
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
#line 511 "LMDB.xs"
	MDB_stat    stat;
#line 1680 "LMDB.c"
	HV *	RETVAL;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_stat",
			"txn", "LMDB::Txn")
;
#line 513 "LMDB.xs"
	populateStat(aTHX_ &RETVAL, mdb_stat(txn, dbi, &stat), &stat);
#line 1694 "LMDB.c"
        ST(0) = newRV_noinc((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__dbi_flags); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__dbi_flags)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "txn, dbi, flags");
    {
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	unsigned int	flags;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_dbi_flags",
			"txn", "LMDB::Txn")
;

	RETVAL = mdb_dbi_flags(txn, dbi, &flags);
#line 523 "LMDB.xs"
	ProcError(RETVAL);
#line 1729 "LMDB.c"
	sv_setuv(ST(2), (UV)flags);
	SvSETMAGIC(ST(2));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__dbi_close); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__dbi_close)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, dbi");
    {
	LMDB__Env	env;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_dbi_close",
			"env", "LMDB::Env")
;

	mdb_dbi_close(env, dbi);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_LMDB_File__drop); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__drop)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "txn, dbi, del");
    {
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	int	del = (int)SvIV(ST(2))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_drop",
			"txn", "LMDB::Txn")
;

	RETVAL = mdb_drop(txn, dbi, del);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__get); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__get)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "txn, dbi, key, data");
    {
#line 568 "LMDB.xs"
	dMY_MULTICALL;
#line 1806 "LMDB.c"
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	DBK	key;
	DBD	data;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_get",
			"txn", "LMDB::Txn")
;

	 PRED_FLGS;

	if (ISDBKINT) {
	    SvIV_please(ST(2));
	    key.mv_data = &(((XPVIV*)SvANY(ST(2)))->xiv_iv);
	    key.mv_size = sizeof(MyInt);
	}
	else key.mv_data = SvPV(ST(2), key.mv_size)
;
#line 575 "LMDB.xs"
	MY_PUSH_MULTICALL;
#line 1836 "LMDB.c"

	RETVAL = mdb_get(txn, dbi, &key, &data);
#line 577 "LMDB.xs"
	MY_POP_MULTICALL;
	ProcError(RETVAL);
#line 1842 "LMDB.c"
	sv_setstatic(aTHX_ ST(3), &data);
	SvSETMAGIC(ST(3));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__put); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__put)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "txn, dbi, key, data, flags");
    {
#line 585 "LMDB.xs"
	dMY_MULTICALL;
#line 1860 "LMDB.c"
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	DBK	key;
	DBD	data;
	flags_t	flags =	SvOK(ST(4)) ? (flags_t)SvUV(ST(4)) : 0
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_put",
			"txn", "LMDB::Txn")
;

	 PRED_FLGS;

	if (ISDBKINT) {
	    SvIV_please(ST(2));
	    key.mv_data = &(((XPVIV*)SvANY(ST(2)))->xiv_iv);
	    key.mv_size = sizeof(MyInt);
	}
	else key.mv_data = SvPV(ST(2), key.mv_size)
;

	if (ISDBDINT) {
	    SvIV_please(ST(3));
	    data.mv_data = &(((XPVIV*)SvANY(ST(3)))->xiv_iv);
	    data.mv_size = sizeof(MyInt);
	}
	else data.mv_data = MySvPV(ST(3), data.mv_size)
;
#line 593 "LMDB.xs"
	if(flags & MDB_RESERVE) /* TODO */
	    croak("MDB_RESERVE flag unimplemented.");
	MY_PUSH_MULTICALL;
#line 1902 "LMDB.c"

	RETVAL = mdb_put(txn, dbi, &key, &data, flags);
#line 597 "LMDB.xs"
	MY_POP_MULTICALL;
	ProcError(RETVAL);
#line 1908 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__del); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__del)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "txn, dbi, key, data");
    {
#line 603 "LMDB.xs"
	dMY_MULTICALL;
#line 1924 "LMDB.c"
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	DBK	key;
	DBD	data;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_del",
			"txn", "LMDB::Txn")
;

	 PRED_FLGS;

	if (ISDBKINT) {
	    SvIV_please(ST(2));
	    key.mv_data = &(((XPVIV*)SvANY(ST(2)))->xiv_iv);
	    key.mv_size = sizeof(MyInt);
	}
	else key.mv_data = SvPV(ST(2), key.mv_size)
;

	if (ISDBDINT) {
	    SvIV_please(ST(3));
	    data.mv_data = &(((XPVIV*)SvANY(ST(3)))->xiv_iv);
	    data.mv_size = sizeof(MyInt);
	}
	else data.mv_data = MySvPV(ST(3), data.mv_size)
;
#line 610 "LMDB.xs"
	MY_PUSH_MULTICALL;
#line 1962 "LMDB.c"
#line 612 "LMDB.xs"
	RETVAL = mdb_del(txn, dbi, &key, (SvOK(ST(3)) ? &data : NULL));
	MY_POP_MULTICALL;
	ProcError(RETVAL);
#line 1967 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__cmp); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__cmp)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "txn, dbi, a, b");
    {
#line 621 "LMDB.xs"
	dMY_MULTICALL;
#line 1983 "LMDB.c"
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	DBD	a;
	DBD	b;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_cmp",
			"txn", "LMDB::Txn")
;

	 PRED_FLGS;

	if (ISDBDINT) {
	    SvIV_please(ST(2));
	    a.mv_data = &(((XPVIV*)SvANY(ST(2)))->xiv_iv);
	    a.mv_size = sizeof(MyInt);
	}
	else a.mv_data = MySvPV(ST(2), a.mv_size)
;

	if (ISDBDINT) {
	    SvIV_please(ST(3));
	    b.mv_data = &(((XPVIV*)SvANY(ST(3)))->xiv_iv);
	    b.mv_size = sizeof(MyInt);
	}
	else b.mv_data = MySvPV(ST(3), b.mv_size)
;
#line 628 "LMDB.xs"
	MY_PUSH_MULTICALL;
#line 2021 "LMDB.c"

	RETVAL = mdb_cmp(txn, dbi, &a, &b);
#line 630 "LMDB.xs"
	MY_POP_MULTICALL;
#line 2026 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File__dcmp); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File__dcmp)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "txn, dbi, a, b");
    {
#line 635 "LMDB.xs"
	dMY_MULTICALL;
#line 2042 "LMDB.c"
	LMDB__Txn	txn;
	LMDB	dbi = *(LMDB *)SvPV_nolen(ST(1))
;
	DBD	a;
	DBD	b;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Txn")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    txn = INT2PTR(LMDB__Txn,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::_dcmp",
			"txn", "LMDB::Txn")
;

	 PRED_FLGS;

	if (ISDBDINT) {
	    SvIV_please(ST(2));
	    a.mv_data = &(((XPVIV*)SvANY(ST(2)))->xiv_iv);
	    a.mv_size = sizeof(MyInt);
	}
	else a.mv_data = MySvPV(ST(2), a.mv_size)
;

	if (ISDBDINT) {
	    SvIV_please(ST(3));
	    b.mv_data = &(((XPVIV*)SvANY(ST(3)))->xiv_iv);
	    b.mv_size = sizeof(MyInt);
	}
	else b.mv_data = MySvPV(ST(3), b.mv_size)
;
#line 642 "LMDB.xs"
	MY_PUSH_MULTICALL;
#line 2080 "LMDB.c"

	RETVAL = mdb_dcmp(txn, dbi, &a, &b);
#line 644 "LMDB.xs"
	MY_POP_MULTICALL;
#line 2085 "LMDB.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File_reader_check); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File_reader_check)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "env, dead");
    {
	LMDB__Env	env;
	int	dead = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "LMDB::Env")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    env = INT2PTR(LMDB__Env,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"LMDB_File::reader_check",
			"env", "LMDB::Env")
;

	RETVAL = mdb_reader_check(env, &dead);
	sv_setiv(ST(1), (IV)dead);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File_strerror); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File_strerror)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "err");
    {
	int	err = (int)SvIV(ST(0))
;
	char *	RETVAL;
	dXSTARG;

	RETVAL = mdb_strerror(err);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_LMDB_File_version); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_LMDB_File_version)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "major, minor, patch");
    {
	int	major;
	int	minor;
	int	patch;
	char *	RETVAL;
	dXSTARG;

	RETVAL = mdb_version(&major, &minor, &patch);
	sv_setiv(ST(0), (IV)major);
	SvSETMAGIC(ST(0));
	sv_setiv(ST(1), (IV)minor);
	SvSETMAGIC(ST(1));
	sv_setiv(ST(2), (IV)patch);
	SvSETMAGIC(ST(2));
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_LMDB_File); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_LMDB_File)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("LMDB::Env::create", XS_LMDB__Env_create, file);
        newXS("LMDB::Env::open", XS_LMDB__Env_open, file);
        newXS("LMDB::Env::copy", XS_LMDB__Env_copy, file);
        newXS("LMDB::Env::copyfd", XS_LMDB__Env_copyfd, file);
        newXS("LMDB::Env::stat", XS_LMDB__Env_stat, file);
        newXS("LMDB::Env::info", XS_LMDB__Env_info, file);
        newXS("LMDB::Env::sync", XS_LMDB__Env_sync, file);
        newXS("LMDB::Env::close", XS_LMDB__Env_close, file);
        newXS("LMDB::Env::set_flags", XS_LMDB__Env_set_flags, file);
        newXS("LMDB::Env::get_flags", XS_LMDB__Env_get_flags, file);
        newXS("LMDB::Env::get_path", XS_LMDB__Env_get_path, file);
        newXS("LMDB::Env::set_mapsize", XS_LMDB__Env_set_mapsize, file);
        newXS("LMDB::Env::set_maxreaders", XS_LMDB__Env_set_maxreaders, file);
        newXS("LMDB::Env::get_maxreaders", XS_LMDB__Env_get_maxreaders, file);
        newXS("LMDB::Env::set_maxdbs", XS_LMDB__Env_set_maxdbs, file);
        newXS("LMDB::Env::get_maxkeysize", XS_LMDB__Env_get_maxkeysize, file);
        newXS("LMDB::Env::id", XS_LMDB__Env_id, file);
        newXS("LMDB::Txn::_begin", XS_LMDB__Txn__begin, file);
        newXS("LMDB::Txn::_env", XS_LMDB__Txn__env, file);
        newXS("LMDB::Txn::_commit", XS_LMDB__Txn__commit, file);
        newXS("LMDB::Txn::_abort", XS_LMDB__Txn__abort, file);
        newXS("LMDB::Txn::_reset", XS_LMDB__Txn__reset, file);
        newXS("LMDB::Txn::_renew", XS_LMDB__Txn__renew, file);
        newXS("LMDB::Txn::_id", XS_LMDB__Txn__id, file);
        newXS("LMDB::Cursor::open", XS_LMDB__Cursor_open, file);
        newXS("LMDB::Cursor::close", XS_LMDB__Cursor_close, file);
        newXS("LMDB::Cursor::count", XS_LMDB__Cursor_count, file);
        newXS("LMDB::Cursor::dbi", XS_LMDB__Cursor_dbi, file);
        newXS("LMDB::Cursor::del", XS_LMDB__Cursor_del, file);
        newXS("LMDB::Cursor::renew", XS_LMDB__Cursor_renew, file);
        newXS("LMDB::Cursor::txn", XS_LMDB__Cursor_txn, file);
        newXS("LMDB::Cursor::_get", XS_LMDB__Cursor__get, file);
        newXS("LMDB::Cursor::_put", XS_LMDB__Cursor__put, file);
        newXS("LMDB_File::constant", XS_LMDB_File_constant, file);
        newXS("LMDB_File::_setcurrent", XS_LMDB_File__setcurrent, file);
        newXS("LMDB_File::_dbi_open", XS_LMDB_File__dbi_open, file);
        newXS("LMDB_File::_stat", XS_LMDB_File__stat, file);
        newXS("LMDB_File::_dbi_flags", XS_LMDB_File__dbi_flags, file);
        newXS("LMDB_File::_dbi_close", XS_LMDB_File__dbi_close, file);
        newXS("LMDB_File::_drop", XS_LMDB_File__drop, file);
        newXS("LMDB_File::_get", XS_LMDB_File__get, file);
        newXS("LMDB_File::_put", XS_LMDB_File__put, file);
        newXS("LMDB_File::_del", XS_LMDB_File__del, file);
        newXS("LMDB_File::_cmp", XS_LMDB_File__cmp, file);
        newXS("LMDB_File::_dcmp", XS_LMDB_File__dcmp, file);
        newXS("LMDB_File::reader_check", XS_LMDB_File_reader_check, file);
        newXS("LMDB_File::strerror", XS_LMDB_File_strerror, file);
        newXS("LMDB_File::version", XS_LMDB_File_version, file);

    /* Initialisation Section */

#line 678 "LMDB.xs"
    MY_CXT_INIT;
    MY_CXT.my_asv = get_sv("::a", GV_ADDMULTI);	    
    MY_CXT.my_bsv = get_sv("::b", GV_ADDMULTI);	    
    my_lasterr = gv_fetchpv("LMDB_File::last_err", 0, SVt_IV);
    my_errgv = gv_fetchpv("LMDB_File::die_on_err", 0, SVt_IV);

#line 2246 "LMDB.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

